### ISSUE TITLE
Negated queries

### ISSUE THREAD

**Issue by mtimofiiv** [mgmco/api-query-spec#1]
A query searching for a field that does _not_ match a pattern should be included. Perhaps a good way of doing this is to use the `!` character in the query to negate it, just before the value.

Example:

`/users?status=!deleted`

**Comment by mtimofiiv** [comment]
cc @chrissvo

**Comment by mtimofiiv** [comment]
This has been implemented and is on the spec page as well

**Comment by adriaandotcom** [comment]
2015! Wow

**Comment by mtimofiiv** [comment]
WorkFast™

**Comment by adriaandotcom** [comment]
No comments of @chrissvo?
